apiVersion: v1
kind: Service
metadata:
  name: gotwitter-spring
  labels:
    app: gotwitter-spring
spec:
  ports:
    - port: 3000
      targetPort: 3000
#      nodePort: 32001
  selector:
    app: gotwitter-spring
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotwitter-spring
spec:
  selector:
    matchLabels:
      app: gotwitter-spring
  replicas: 2
  template:
    metadata:
      labels:
        app: gotwitter-spring
    spec:
      containers:
        - name: gotwitter-spring
          image: "douglasso/gotwitter-spring"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
